version: 1
build:
  main: cmd/arda-pocd
validation: sovereign
accounts:
  - name: ERES
    coins:
      - 200000000uarda
      - 200000000usdarda
  - name: Bank
    coins:
      - 200000000usdarda
  - name: AIX
    coins:
      - 1000000usdarda
  - name: DLD
    coins:
      - 200000000usdarda
  - name: Fatima_Developers
    coins:
      - 1000000usdarda
  - name: matt
    coins:
      - 1000000usdarda
  - name: oli
    coins:
      - 1000000usdarda
  - name: toby
    coins:
      - 1000000usdarda
  - name: fawad
    coins:
      - 1000000usdarda
  - name: siddiq
    coins:
      - 1000000usdarda
  - name: mohammad
    coins:
      - 1000000usdarda
  - name: ahmed
    coins:
      - 1000000usdarda
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: Bank
  coins:
    - 100000usdarda
validators:
  - name: ERES
    bonded: 100000000uarda
    config:
      moniker: "ERES Validator"
    client:
      output: "json"
