version: 1
validation: sovereign
accounts: 
- name: ERES
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: ERES
  bonded: 100000000stake
  config:
    moniker: "ERES Validator"
  client:
    output: "json"
