version: 1
validation: sovereign
accounts: 
- name: ERES
  coins:
  - 20000token
  - 200000000uarda
- name: bob
  coins:
  - 10000token
  - 100000000uarda
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000uarda
validators:
- name: ERES
  bonded: 100000000uarda
  config:
    moniker: "ERES Validator"
  client:
    output: "json"
