version: "3.9"

services:
  arda:
    build:
      context: .
      dockerfile: Dockerfile
    image: arda-pocd
    ports:
      - "26657:26657"   # Tendermint RPC
      - "1317:1317"     # REST API
      - "9090:9090"     # gRPC
      - "4500:4500"     # Faucet
    volumes:
      - arda_state:/app/.arda-poc            # <-- named volume, not host bind
    environment:
      - ARDA_HOME=/data/.arda-poc       # entrypoint.sh uses this
    # Healthy only after height > 1
    # healthcheck:
    #   test: >
    #     CMD sh -c "
    #       h=$(curl -sf http://localhost:26657/status |
    #            grep -o '\"latest_block_height\":\"[0-9]*\"' |
    #            grep -o '[0-9]*') &&
    #       [ \"$h\" -gt 1 ]
    #     "
    #   interval: 10s
    #   timeout: 5s
    #   retries: 12      # ~2 min max wait

  sidecar:
    build:
      context: .
      dockerfile: cmd/tx-sidecar/Dockerfile
    image: tx-sidecar-compose
    # depends_on:
      # arda:
        # condition: service_healthy
    volumes:
      - arda_state:/app/.arda-poc            # share chain state
      - sidecar_data:/app/local_data         # own DB
    ports:
      - "8080:8080"
    command: ["./tx-sidecar"]

volumes:
  arda_state:
  sidecar_data:
