# Build stage
FROM golang:1.21-alpine AS build
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/arda-pocd ./cmd/arda-pocd

# Runtime stage
FROM alpine:3.18
RUN apk add --no-cache bash
COPY --from=build /bin/arda-pocd /usr/local/bin/arda-pocd
COPY docker/entrypoint-fullnode.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 26656 26657
ENV CHAIN_ID=ardapoc
VOLUME ["/root/.arda-poc","/genesis"]
ENTRYPOINT ["/entrypoint.sh"]
CMD ["start"]
