# This is the base compose file and is configured to run published images.
# For local development (building from source), use the override file:
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
services:
  arda:
    image: ghcr.io/ardaglobal/arda-poc:${IMAGE_TAG:-latest}
    ports:
      - "26657:26657"   # Tendermint RPC
      - "1317:1317"     # REST API
      - "9090:9090"     # gRPC
      - "4500:4500"     # Faucet
    volumes:
      - arda_state:/data
    environment:
      - ARDA_HOME=/data/.arda-poc

  sidecar:
    image: ghcr.io/ardaglobal/arda-poc-tx-sidecar:${IMAGE_TAG:-latest}
    volumes:
      - arda_state:/data            # share chain state
      - sidecar_data:/app/local_data         # own DB
    ports:
      - "8080:8080"
    environment:
      - BLOCKCHAIN_REST_API_URL=http://arda:1317
      - GRPC_ADDR=arda:9090
      - NODE_RPC_URL=http://arda:26657
      - FAUCET_URL=http://arda:4500
      - ARDA_HOME=/data/.arda-poc
    depends_on:
      - arda

volumes:
  arda_state:
  sidecar_data:
