name: Build and Push Docker Images

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_APP: ${{ github.repository }}/arda-pocd
  IMAGE_NAME_SIDECAR: ${{ github.repository }}/tx-sidecar

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for main app
      id: meta-app
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_APP }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,prefix=sha-

    - name: Extract metadata for tx-sidecar
      id: meta-sidecar
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SIDECAR }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,prefix=sha-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push main app image
      id: build-app
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta-app.outputs.tags }}
        labels: ${{ steps.meta-app.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push tx-sidecar image
      id: build-sidecar
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./cmd/tx-sidecar/Dockerfile
        push: true
        tags: ${{ steps.meta-sidecar.outputs.tags }}
        labels: ${{ steps.meta-sidecar.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image digests
      run: |
        echo "Main app image digest: ${{ steps.build-app.outputs.digest }}"
        echo "TX-sidecar image digest: ${{ steps.build-sidecar.outputs.digest }}"